# Generated by Django 5.2.1 on 2025-05-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=200)),
                ('is_completed', models.BooleanField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minha_estante.autores')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minha_estante.categoria')),
            ],
        ),
    ]
