# Generated by Django 5.2.1 on 2025-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_estante', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autores',
            new_name='Autor',
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(),
        ),
    ]
