# Generated by Django 5.2.1 on 2025-05-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minha_estante', '0002_rename_autores_autor_alter_livro_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='is_completed',
        ),
    ]
