# Generated by Django 5.2.1 on 2025-05-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_estante', '0003_remove_livro_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('lido', 'Lido'), ('lendo', 'Lendo'), ('quero_ler', 'Quero Ler')], default='quero_ler', max_length=20),
        ),
    ]
